version: '3'
services:
  client:
    container_name: appname-client
    # Point build step to the client directory
    build: 'client'
    ports:
      # Add the port that the client application runs on - (port:port).
      - '3000:3000'
    depends_on:
      - server
  server:
    container_name: appname-server
    # Point build step to the server directory
    build: 'server'
    ports:
      # Add the port that the server application runs on - (port:port).
      - '8080:8080'
    depends_on:
      - database
  database:
    container_name: appname-database
        # Point build step to the server directory
    build: 'database'
    ports:
      # Add the port that the database application runs on - (port:port).
      - '27017:27017'