version: '3'
services:
  client:
    container_name: appname-client
    # client, frontend, app ui
    build:
      context: client # build from \client
    ports:
      - '3000:3000'
    restart: always
    networks:
      - react-express # client to server connection
    depends_on:
      - server
  server:
    container_name: appname-server
    # server, backend, app internals
    build:
      context: server # build from \server
    ports:
      - '8080:8080'
    restart: always
    networks:
      - react-express # client to server connection
      - express-mongo # server to database connection
    depends_on:
      - database
  database:
    container_name: appname-database
    # database, db, data store, app persistent data
    build:
      context: database # build from \database
    ports:
      - '27017:27017'
    restart: always
    networks:
      - express-mongo # server to database connection
networks:
  react-express:
  express-mongo: