#      Title:    MicroCODE Dockerfile for MERN App - BACKEND
#      Module:   Modules (./dockerfile)
#      Customer: Internal
#      Creator:  MicroCODE Incorporated
#      Date:     August 2022
#      Author:   Timothy J McGuire
#
#      Designed and Coded: 2022 MicroCODE Incorporated
#
#      This software and related materials are the property of
#      MicroCODE Incorporated and contain confidential and proprietary
#      information. This software and related materials shall not be
#      duplicated, disclosed to others, or used in any way without the
#      written of MicroCODE Incorported.
#
#
#      DESCRIPTION:
#      ------------
#
#      This module implements the Dockerization of a MERN Backend/Server.
#
#
#      REFERENCES:
#      -----------
#
#      1. DOCKER Documentation
#         https://docs.docker.com/docker-hub/
#
#
#
#      MODIFICATIONS:
#      --------------
#
#  Date:         By-Group:   Rev:     Description:
#
#  13-Aug-2022   TJM-MCODE  {0001}    New file for learning DOCKER-ization.
#  27-Sep-2022   TJM-MCODE  {0002}    Updated to use .env APP_* variables.
#
#
#
# use official NodeJS image
FROM node:14-slim
#
# signature
LABEL ${APP_NAME}.backend.constructor=${APP_CONSTRUCTOR}
#
# bring in the Node JS environment 'development' or 'production'
ARG NODE_ENV
ENV NODE_ENV ${NODE_ENV}
#
# set container’s working directory
WORKDIR /app
#
# copy Node dependencies for NPM
COPY package.json /app/package.json
#
# install all Node dependencies
RUN npm install
#
# copy all App source code
COPY . .
#
# expose port and start the application
EXPOSE ${APP_BACKEND_PORT}
#
CMD ["npm", "start"]