name: CI/CD for AppName
on:
  push:
    branches:
      - main
jobs:
  build:
    # B U I L D
    name: BUILD
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14]
    steps:
      -
        name: BUILD - CHECK-OUT CODE TO VM
        uses: actions/checkout@v3
      -
        name: BUILD - SET-UP NODE ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      -
        name: BUILD - DOCKER COMPOSE
        uses: isbang/compose-action@v1.2.0
        with:
            compose-file: "docker-compose.yml"
        env:
          CI: true
          COMPOSE_PROJECT_NAME: mit-xpro-appname
  deploy:
    # D E P L O Y
    name: DEPLOY
    needs: build
    runs-on: ubuntu-latest
    steps:
      -
        name: DEPLOY - CHECK-OUT CODE
        uses: actions/checkout@v3
      -
        name: DEPLOY - LOG-IN DOCKER HUB
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      -
        name: DEPLOY - GET DOCKER VERSION
        run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})
      -
        name: BUILD + PUSH
        run: |
          docker push mit-xpro-appname/mongo
          docker push mit-xpro-appname/server
          docker push mit-xpro-appname/client